# Setup
name:         Paper Jet Plane!
tagline:      Imagine the fun in flying a paper airplane!
baseurl:      ""

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

theme: jekyll-theme-architect